/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package ka10

class Library {
    companion object {
        @JvmStatic
        fun main(args: Array<String>) {
            println("DEV")
        }
    }
    fun someLibraryMethod(): Boolean {
        return true
    }
}
